name: cache workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - uses: actions/checkout@v4
      - name: cache node_modules
        id: cache-step
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-file-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | #надо чтобы с нуля все пакеты не качать, какие-то уже будут
            ${{ runner.os }}-cache-file
            ${{ runner.os }}-
      - name: display cache
        run: echo "${{ toJSON(steps.cache-step.outputs) }}"
      - name: install npm modules
        run: npm install
