name: secrets workflow
on: [push]

jobs:
  run-command:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: my vars and secrets
        run: |
          echo "${{ vars.STATUS }}"
          echo "${{ secrets.PASSWORD }}"
