name: timeout workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1 #можно лимитить на уровне job
    steps:
      - name: sleep
        run: sleep 200
        #timeout-minutes: 1
        #можно лимитировать на уровне стэпа