name: vars workflow
on: [push]
env:
  CUSTOM_VAR: 1 #доступна во всем файле

jobs:
  run-command:
    runs-on: ubuntu-latest
    env:
      JOB_CUSTOM_VAR: 1 #доступна на уровне job
    steps:
      - name: set new var
        run: echo "NEW_CUSTOM_VAR=new" >> "$GITHUB_ENV"
      - name: set new var
        env:
          STEP_CUSTOM_VAR: STEP 1 #доступна на уровне step
          CUSTOM_VAR: 1 + 2 - STEP 2 #перезаписали
        run: |
          echo $GITHUB_REF
          echo "${{ github.ref }}" #сразу будет готовое значение в echo
          echo $CUSTOM_VAR
          echo "${{ env.CUSTOM_VAR }}"
          echo $JOB_CUSTOM_VAR
          echo $STEP_CUSTOM_VAR
